config/routes.rb
CharitySearch::Application.routes.draw do
  get "charity_service/index"
  root :to => "charity_service#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  def self.search(search_terms)
    # To be implemented later
    self.where(true)
  end

  # Get the whole hash of the associated Charity
  def charity_hash
    unless @charity
      require "#{Rails.root}/lib/CharityDataProvider.rb"
      @charity = CharityDataProvider.find(charity_id)
      # Empty hash if nothing returned
      @charity = {} unless @charity
    end
    @charity
  end
end

app/models/charity.rb
class Charity
  def self.search(search_terms)
    # To be implemented later
    mock_data
  end

  # Find a specific charity by ein
  def self.find(ein)
    mock_data.select {|charity| charity[:ein] == ein}.first
  end

  def self.get_image_url(ein)
    # To be implemented later
    "http://rubyonrails.org/images/rails.png"
  end

  private

  def self.mock_data
    data = []
    100.times do |i|
      data <<  {:ein => i, :orgName => "Charity #{i}", :description => "Lorem ipsum dolor sit amet, consectetur adipiscing elit."}
    end
    data
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charity_service_controller.rb
class CharityServiceController < ApplicationController
  def index
    @search_terms = params[:search_terms]
    if not @search_terms.blank?
      require "#{Rails.root}/lib/CharityDataProvider.rb"
      require "#{Rails.root}/lib/CharityService.rb"
      @campaigns = Campaign.search(@search_terms).page params[:campaigns_page]
      @charities = CharityDataProvider.search @search_terms
      @charities = Kaminari.paginate_array(@charities).page params[:charities_page]
    end
    @selection_url = params[:selection_url]
    @cancellation_url = params[:cancellation_url]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def append_query_string(url, key, value)
    "#{url}#{url.index('?') ? '&' : '?'}#{key}=#{value}"
  end
end

app/views/campaigns/_campaign.html.erb
<tr>
  <td>
    <%= campaign.name %>
  </td>
  <td>
    <%= campaign.description %>
  </td>
  <td>
    <%= image_tag CharityService.get_campaign_image_url(campaign.id), :size => "32x40" %>
  </td>
  <td>
    <%= campaign.charity_hash[:orgName] %>
  </td>
  <td>
    <%= campaign.charity_hash[:description] %>
  </td>
  <td>
    <%= image_tag CharityService.get_charity_image_url(campaign.charity_id), :size => "32x40"%>
  </td>

  <td>
    <%= link_to("Select", append_query_string(@selection_url,"campaign_id",campaign.id)) unless @selection_url.blank? %>
  </td>
</tr>

app/views/charities/_charity.html.erb
<tr>
  <td>
    <%= charity[:orgName] %>
  </td>
  <td>
    <%= charity[:description] %>
  </td>
  <td>
    <%= image_tag CharityService.get_charity_image_url(charity[:ein]), :size => "32x40"%>
  </td>
  <td>
      <%= link_to("Select", append_query_string(@selection_url, "charity_id", charity[:ein])) unless @selection_url.blank? %>
  </td>
</tr>

app/views/charity_service/index.html.erb
<h1>Search Charities and Campaigns</h1>
<div style="border: solid 2px #0A0; padding:8px; width:50%">Keep search box blank to show "no results" view.  Enter anything else to see full results view.</div>
<br/>
<div id="charity_search">
  <%= form_tag(charity_service_index_path, :method => "get") do %>
    <%= text_field_tag(:search_terms, @search_terms || "") %>
    <%= hidden_field_tag(:cancellation_url, @cancellation_url) unless @cancellation_url.blank? %>
    <%= hidden_field_tag(:selection_url, @selection_url) unless @selection_url.blank? %>
    <%= submit_tag "Do Some Good", :name => "submit" %>
  <%end%>
</div>
<% if @cancellation_url %>
  <br/>
  <%= link_to "Cancel", @cancellation_url %>
<%end%>
<hr/>
<div id="charity_results">
  <% if @campaigns || @charities %>
    <h2>Campaigns matching '<%= @search_terms %>'</h2>
    <table id="campaigns">
      <tr>
        <th>Campaign</th>
        <th>Campaign Description</th>
        <th>Campaign Logo</th>
        <th>Charity</th>
        <th>Charity Description</th>
        <th>Charity Logo</th>
        <th></th>
      </tr>
      <%= render :partial => "campaigns/campaign", :collection => @campaigns %>
    </table>
    <%= paginate @campaigns, :param_name => :campaigns_page %>
    <hr/>
    <h2>Charities matching '<%= @search_terms %>'</h2>
    <table id="charities">
      <tr>
        <th>Charity</th>
        <th>Charity Description</th>
        <th>Charity Logo</th>
        <th></th>
      </tr
      <%= render :partial => "charities/charity", :collection => @charities %>
    </table>
    <%= paginate @charities, :param_name => :charities_page %>
  <%elsif params[:search_terms] %>
    <span id="no_results">You've reached the end of the internet; we couldn't find what you were looking for.</span>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharitySearch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>